apiVersion: v1
kind: Service
metadata:
  labels:
    app: result
  name: result
spec:
  type: LoadBalancer
  ports:
  - name: "result-service"
    port: 80        # Puerto accesible públicamente
    targetPort: 80  # Puerto del contenedor
  selector:
    app: result
